### ISSUE TITLE
maximize window keybinding?

### ISSUE THREAD

**Issue by nunotexbsd** [vardy/aphelia#13]
Hello,

Why not add a key binding to maximize a window?

I feel the need for this option when I open sterm and need to resize it by hand.

Well this is not a big issue but I think this project can maintain its simplicity with this option.

Thanks,

Nuno Teixeira

**Comment by vardy** [comment]
Good morning! I do think this would be helpful - and sorry for replying late - but I'm not in a position or work environment to be working on this project at the moment. If someone else has time to, this is something I can get behind provided that it meets the requirement of minimalism and simplicity necessary.
